version: "3.7"

services:
  
  search-api:
    # Map host machine port 4444 to container port 8080
    # Only root can listen on ports below 1024, we use higher-numbered ports
    # since nginx is running under non-root user hubmap
    ports:
      - "4444:8080"


